name: Pull request
description: Are you looking to contributing to Mina? Do it by following this template.
labels: "type: pullrequest"
body:
  - type: markdown
    attributes:
      value: |
        ### Welcome 👋

        Thank you for contributing to Mina! Please see `CONTRIBUTING.md` if you haven't
        yet. In that doc, there are more details around how to start our CI.

        If you cannot complete any of the steps below, please ask for help from a core
        contributor.

        ### Incomplete Work

        We feel it's important that everyone is comfortable landing incomplete projects
        so we don't keep PRs open for too long (especially on develop). To do this we
        don't want to forget that something is incomplete, don't want to be blocked on
        landing things, and we don't want to land anything that breaks the daemon. We
        don't want to forget to test the incomplete things whenever they are completed,
        and finally we want to clean up after ourselves: any temporary cruft gets
        completely removed before a project is considered done.

        To achieve the above, we wish to keep track of incomplete work using a draft of
        the release notes. We can share this part of the current draft at anytime with
        external contributors. Moreover, we will review this draft during hardforks.

        To ship incomplete work, put it behind feature flags -- prefer a runtime
        CLI/daemon-config-style flag if possible, and only if necessary fallthrough to
        compile time flags. Note that if you put code behind a compile time flag, you
        _must_ ensure that CI is building all possible code paths. Don't land something
        that doesn't build in CI.

        ## PLEASE DELETE EVERYTHING ABOVE THIS LINE
        ---
  - type: textarea
    validations:
      required: true
    attributes:
      label: Summary
      description: |
        Explain your changes
  - type: textarea
    validations:
      required: true
    attributes:
      label: Testing steps
      description: |
        Explain how you tested your changes
  - type: checkboxes
    attributes:
      label: Required Checklist
      description: Please make sure that you verify each checkbox and to follow the instructions for each of them.
      options:
        - label: "Modified the current draft of release notes with details on what is completed or incomplete within this project."
          required: true
        - label: "Documented code purpose and how to use it."
          required: true
        - label: "Mentioned expected invariants and implicit constraints."
          required: true
        - label: "Tests were added for the new behavior."
          required: true
        - label: "Documented test purpose and the significance of failures."
          required: true
        - label: "Test names reflect their purpose."
          required: true
        - label: "All tests pass (CI will check this if you didn't)"
          required: true
        - label: "Serialized types are in stable-versioned modules"
          required: true
        - label: "Does this pull request close more than one issue? List them"
          required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: What issue this pull request closes?
      placeholder: * Closes #0000
      description: |
        This field points to an existing Issue this pull request is addressing.
