name: 🪲 Flaky test
description: Did you find a flaky test in our CI? Report your findings here.
labels: "type: flaky_test"
body:
  - type: markdown
    attributes:
      value: |
        # Welcome 👋

        Thanks for taking the time to fill out this issue.
        Please fill out each section below. This info allows Mina maintainers to triage and fix the flaky test(s) as quickly as possible.

        Useful links:

        - Documentation: https://docs.minaprotocol.com/
        - Contributing: check `CONTRIBUTING.md`
  - type: checkboxes
    attributes:
      label: Preliminary Checks
      description: Please make sure that you verify each checkbox and follow the instructions for them.
      options:
        - label: "This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues"
          required: true
        - label: "This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/issues-experiment/discussions"
          required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: Summary
      description: |
        Describe what test(s) are flaky and how do you think they should behave?
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to replicate this Issue
      description: How can the problem be replicated? Are there any additional steps required?
      value: |
        1.
        2.
        3.
        ...
  - type: textarea
    attributes:
      label: Console output
      render: shell
      description: Paste the output of the test(s) here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Platform
      description: What platform you use. Are there any special flags you are using?
      placeholder: |
        Platform: Ubuntu 21.04
        FLAGS: --XPTO=1
    validations:
      required: true
  - type: textarea
    attributes:
      label: Build link(s)
      description: Provide the CI's URL where the build is failing
    validations:
      required: false
